const mainCardData = [
  {
    name: "@nathanf",
    socialIcon: "bi bi-facebook",
    socialIconStyle: "facebook",
    dataValue: "1987",
    caret: "bi bi-caret-up-fill",
    socialType: "Followers",
    num: "12",
  },
  {
    name: "@nathanf",
    socialIcon: "bi bi-twitter",
    socialIconStyle: "twitter",
    dataValue: "1044",
    caret: "bi bi-caret-up-fill",
    socialType: "Followers",
    num: "99",
  },
  {
    name: "@realnathanf",
    socialIcon: "bi bi-instagram",
    socialIconStyle: "instagram",
    dataValue: "11K",
    caret: "bi bi-caret-up-fill",
    socialType: "Followers",
    num: "1099",
  },
  {
    name: "Nathan F.",
    socialIcon: "bi bi-youtube",
    socialIconStyle: "youtube",
    dataValue: "8239",
    caret: "bi bi-caret-down-fill",
    socialType: "Subscribers",
    num: "-144",
  },
];

const overViewData = [
  {
    dataValue: "87",
    socialIcon: "bi bi-facebook",
    socialIconStyle: "facebook",
    caret: "bi bi-caret-up-fill",
    socialDataType: "Page Views",
    percentage: "3%",
  },
  {
    dataValue: "52",
    socialIcon: "bi bi-facebook",
    socialIconStyle: "facebook",
    caret: "bi bi-caret-down-fill",
    socialDataType: "Likes",
    percentage: "-2%",
  },
  {
    dataValue: "5462",
    socialIcon: "bi bi-instagram",
    socialIconStyle: "instagram",
    caret: "bi bi-caret-up-fill",
    socialDataType: "Likes",
    percentage: "2257%",
  },
  {
    dataValue: "52K",
    socialIcon: "bi bi-instagram",
    socialIconStyle: "instagram",
    caret: "bi bi-caret-up-fill",
    socialDataType: "Profile Views",
    percentage: "1375%",
  },
  {
    dataValue: "117",
    socialIcon: "bi bi-twitter",
    socialIconStyle: "twitter",
    caret: "bi bi-caret-up-fill",
    socialDataType: "Retweets",
    percentage: "303%",
  },
  {
    dataValue: "507",
    socialIcon: "bi bi-twitter",
    socialIconStyle: "twitter",
    caret: "bi bi-caret-up-fill",
    socialDataType: "Likes",
    percentage: "553%",
  },
  {
    dataValue: "107",
    socialIcon: "bi bi-youtube",
    socialIconStyle: "youtube",
    caret: "bi bi-caret-down-fill",
    socialDataType: "Likes",
    percentage: "-19%",
  },
  {
    dataValue: "1407",
    socialIcon: "bi bi-youtube",
    socialIconStyle: "youtube",
    caret: "bi bi-caret-down-fill",
    socialDataType: "Total Views",
    percentage: "-12%",
  },
];

export { mainCardData, overViewData };
